### ISSUE TITLE
Proftp welcome message not supported

### ISSUE THREAD

**Issue by bjoernhaeuser** [Jarlakxen/reactive-ftp#1]
Hi! 

Thanks for this awesome project, really looking forward to use it. I just tried to connect to an locally setup ftp server (https://hub.docker.com/r/stilliard/pure-ftpd/).

The problem is that the response message is not supported:

```
[error] - com.github.jarlakxen.reactive.ftp.client.FtpConnection - Unexpected message 220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
220-You are user number 1 of 5 allowed.
220-Local time is now 20:21. Server port: 21.
220-This is a private system - No anonymous login
220-IPv6 connections are also welcome on this server.
220 You will be disconnected after 15 minutes of inactivity.
.
```

Afterwards the connection is an unusable state an nothing is going to happen. I tried to understand the regex, and as far as I see it `MultilineResponsePattern` only supports two lines.

Thanks!

**Comment by Jarlakxen** [comment]
Hi @bjoernhaeuser !
I'm going to try to work on this issue this week. I was already thinking on moving the test to https://github.com/whisklabs/docker-it-scala and use a docker image with an FTP server

**Comment by Jarlakxen** [comment]
Sorry for the delay, I had a very busy month.
